(* expr = expr, addop, term | term; *)
(* term = term, multiop, factor | factor; *)
expr = term, {addop, term}
term = factor, {multiop, factor}
factor = "(", expr, ")" | literial;
literial = number, [unit];

addop="+"|"-";
multiop="*"|"/";
unit = "m"|"mm"|"cm"|"inch"|"in"|"foot"|"feet"| "ft";


number = digit, {digit}, {".", digit, {digit}};
digit  = "0"-"9";
